// First line consists of number of test cases t. Each test case consists of two strings b1 (blessing 1),
// // b2 (blessing 2) and an integer K, each of them in separate lines.
// //Output consists of t lines each containing
// // an integer denoting the maximum happiness value that can be generated by the two blessings. 
//
#include <bits/stdc++.h>
using namespace std;



int helper(stirng s1,string s2,int k)
{
	int x,y;
	x = s1.length();
	y = s2.length();
	//------------------------3d array dp[i][j][k] ---------------------
	int ***dp = new int**[x+1];
	for(int i=0;i<=x;i++)
	{
		dp[i]= new int *[y+1];
		for(int j=0;j<=y;j++)
		{
			dp[i][j]=new int[k+1];
			for(int l =0;l<=k;l++)
			{
				dp[i][j][k]=-1;
			}
		}

	}




	int ans = helper2(s1,s2,x,y,dp);
//-------------------------------deleting 3d array-------------------------\

}




 int main() {
       int t;
      cin>>t;
         while(t--) 
	 {
		 string s1;
		 string s2;
		 cin>>s1>>s2;
         	 int k;
		 cin>>k;

		 int ans = helper(s1,s2,k);

	 }
return 0;
 }
